server:
  port: 90

spring:
  data:
    rest:
      base-path: /api
    mongodb:
      port: 27017
      database: mazahireuloom
      host: localhost

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

security:
  ignored: "*.js*"